version: '2'
services:
  jenkins:
    build: .
    restart: unless-stopped
    network_mode: "bridge"
    container_name: proxy
    image: reangd/alpine-proxy:latest
    environment:
      #
      # base params:
      #
      - S6_LOGGING=0
      # - SERVICE_CRON=0
      # - RESTORE_NAME=daily.0
      # - NGINX_OPTIONS=...
      #
      # registrator params:
      #
      - SERVICE_NAME=proxy
      - SERVICE_TAGS=
      - SERVICE_CHECK_TCP=true
      - SERVICE_CHECK_INTERVAL=15s
      - SERVICE_CHECK_TIMEOUT=10s
      #
      # proxy params:
      #
      - CERT_EMAIL=admin@example.com
      - CERT_DOMAIN=example.com
      # - CERT_PRODACTION=1
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
    volumes:
      # - ./log:/var/log:rw
      # - ./backup:/backup:rw
      # - ./data:/data:rw
      - /etc/localtime:/etc/localtime:ro
