version: '2'
services:
  mediawiki:
    build: .
    restart: unless-stopped
    network_mode: "bridge"
    container_name: mediawiki
    hostname: mediawiki
    image: reangd/alpine-mediawiki:latest
    environment:
      #
      # base params:
      #
      - S6_LOGGING=0
      # - SERVICE_CRON=1
      # - RESTORE_NAME=daily.0
      # - NGINX_OPTIONS=...
    ports:
      - "80:80"      # HTTP
    volumes:
      # - ./log:/var/log:rw
      # - ./backup:/backup:rw
      # - ./data:/data:rw
      - /etc/localtime:/etc/localtime:ro
