version: '2'
services:
  dokuwiki:
    build: .
    restart: unless-stopped
    network_mode: "bridge"
    container_name: dokuwiki
    image: reangd/alpine-dokuwiki:latest
    environment:
      #
      # base params:
      #
      - S6_LOGGING=0
      # - SERVICE_CRON=1
      # - RESTORE_NAME=daily.0
      # - NGINX_OPTIONS=...
      #
      # registrator params:
      #
      - SERVICE_443_IGNORE=true
      - SERVICE_80_NAME=dokuwiki
      - SERVICE_80_TAGS=public
      - SERVICE_80_CHECK_TCP=true
      - SERVICE_80_CHECK_INTERVAL=15s
      - SERVICE_80_CHECK_TIMEOUT=10s
    # ports:
    #   - "80:80"      # HTTP
    volumes:
      # - ./log:/var/log:rw
      # - ./backup:/backup:rw
      # - ./data:/data:rw
      - /etc/localtime:/etc/localtime:ro
